version: "3"
services:
  app:
    container_name: form_validator_app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - form_validator_mongodb
    restart: on-failure
  form_validator_mongodb:
    container_name: form_validator_mongodb
    image: mongo
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: